dockerfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -20,6 +20,54 @@ pipeline {
 				echo "Code Package is completed"
 				}
 			}
+	        stage('Build & Tag Docker Image') {
+                steps {
+                    echo 'Building Docker Image with Tags...'
+                    sh "docker build -t deserthawk97/booking-ms:latest -t booking-ms:latest ."
+                    echo 'Docker Image Build Completed!'
+                }
+            }
+            stage('Docker Image Scanning') {
+                steps {
+                    echo 'Scanning Docker Image with Trivy...'
+                    sh 'trivy image deserthawk97/booking-ms:latest || echo "Scan Failed - Proceeding with Caution"'
+                    echo 'Docker Image Scanning Completed!'
+                }
+            }
+            stage('Push Docker Image to Docker Hub') {
+                steps {
+                    script {
+                        withCredentials([string(credentialsId: 'dockerhubCred', variable: 'dockerhubCred')]) {
+                            sh 'docker login docker.io -u deserthawk97 -p ${dockerhubCred}'
+                            echo 'Pushing Docker Image to Docker Hub...'
+                            sh 'docker push deserthawk97/booking-ms:latest'
+                            echo 'Docker Image Pushed to Docker Hub Successfully!'
+                        }
+                    }
+                }
+            }
+            stage('Push Docker Image to Amazon ECR') {
+                steps {
+                    script {
+                        withDockerRegistry([credentialsId: 'ecr:ap-south-1:ecr-upload-credentials', url: "https://533267238276.dkr.ecr.ap-south-1.amazonaws.com"]) {
+                            echo 'Tagging and Pushing Docker Image to ECR...'
+                            sh '''
+                                docker images
+                                docker tag booking-ms:latest 533267238276.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest
+                                docker push 533267238276.dkr.ecr.ap-south-1.amazonaws.com/booking-ms:latest
+                            '''
+                            echo 'Docker Image Pushed to Amazon ECR Successfully!'
+                        }
+                    }
+                }
+    		}
+            stage('Cleanup Docker Images') {
+                steps {
+                    echo 'Cleaning up local Docker images...'
+                    sh 'docker rmi -f $(docker images -aq)'
+                    echo 'Local Docker images deleted successfully!'
+                }
+            }
 		}
 }
 
